import type { 
  User, 
  Project, 
  Task, 
  Supplier, 
  Delivery, 
  TaskChangeProposal, 
  UserRole 
} from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    full_name: 'Mike Thompson',
    email: 'mike@example.com',
    role: 'project_manager',
    avatar_url: 'https://randomuser.me/api/portraits/men/1.jpg',
    company: 'BuildTech Construction',
    phone: '+1-555-0123',
    specialties: ['Project Management', 'Construction'],
    created_at: new Date('2023-01-15'),
    updated_at: new Date()
  },
  {
    id: '2',
    full_name: 'Sarah Wilson',
    email: 'sarah@example.com',
    role: 'project_coordinator',
    avatar_url: 'https://randomuser.me/api/portraits/women/2.jpg',
    company: 'BuildTech Construction',
    phone: '+1-555-0124',
    specialties: ['Coordination', 'Quality Control'],
    created_at: new Date('2023-02-20'),
    updated_at: new Date()
  },
  {
    id: '3',
    full_name: 'Jake Rodriguez',
    email: 'jake@example.com',
    role: 'subcontractor',
    avatar_url: 'https://randomuser.me/api/portraits/men/3.jpg',
    company: 'Rodriguez Construction',
    phone: '+1-555-0125',
    specialties: ['Concrete', 'Structural Work'],
    created_at: new Date('2023-03-10'),
    updated_at: new Date()
  },
  {
    id: '4',
    full_name: 'Lisa Chen',
    email: 'lisa@example.com',
    role: 'supplier',
    avatar_url: 'https://randomuser.me/api/portraits/women/4.jpg',
    company: 'Chen Supplies',
    phone: '+1-555-0126',
    specialties: ['Materials', 'Logistics'],
    created_at: new Date('2023-04-05'),
    updated_at: new Date()
  },
  {
    id: '5',
    full_name: 'David Park',
    email: 'david@example.com',
    role: 'viewer',
    avatar_url: 'https://randomuser.me/api/portraits/men/5.jpg',
    company: 'Client Corp',
    phone: '+1-555-0127',
    specialties: ['Client Representative'],
    created_at: new Date('2023-05-01'),
    updated_at: new Date()
  }
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Metro Materials Co.',
    company: 'Metro Materials Co.',
    email: 'orders@metromatierals.com',
    phone: '+1-555-0200',
    address: '123 Industrial Ave, Metro City',
    specialties: ['Concrete', 'Steel', 'Lumber'],
    is_active: true,
    rating: 4.5,
    created_at: new Date('2023-01-01'),
    updated_at: new Date()
  },
  {
    id: '2',
    name: 'Steel Works Inc.',
    company: 'Steel Works Inc.',
    email: 'info@steelworks.com',
    phone: '+1-555-0201',
    address: '456 Steel Street, Metro City',
    specialties: ['Steel', 'Rebar', 'Structural Elements'],
    is_active: true,
    rating: 4.8,
    created_at: new Date('2023-01-15'),
    updated_at: new Date()
  },
  {
    id: '3',
    name: 'Electric Supply Co.',
    company: 'Electric Supply Co.',
    email: 'sales@electricsupply.com',
    phone: '+1-555-0202',
    address: '789 Electric Blvd, Metro City',
    specialties: ['Electrical', 'Wiring', 'Fixtures'],
    is_active: true,
    rating: 4.2,
    created_at: new Date('2023-02-01'),
    updated_at: new Date()
  }
];

export const mockTasks: Task[] = [
  {
    id: '1',
    project_id: 'proj-1',
    title: 'Site Preparation',
    description: 'Clear and prepare the construction site',
    category: 'Site Work',
    location: 'Main Site',
    status: 'completed',
    priority: 'high',
    assigned_to: '3',
    start_date: new Date('2024-01-15'),
    end_date: new Date('2024-01-22'),
    actual_start_date: new Date('2024-01-15'),
    actual_end_date: new Date('2024-01-21'),
    planned_duration: 7,
    actual_duration: 6,
    progress_percentage: 100,
    color: '#22c55e',
    dependencies: [],
    notes: 'Completed ahead of schedule',
    created_by: '1',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-21')
  },
  {
    id: '2',
    project_id: 'proj-1',
    title: 'Foundation Excavation',
    description: 'Excavate for building foundation',
    category: 'Foundation',
    location: 'Building A',
    status: 'completed',
    priority: 'critical',
    assigned_to: '3',
    start_date: new Date('2024-01-23'),
    end_date: new Date('2024-01-26'),
    actual_start_date: new Date('2024-01-23'),
    actual_end_date: new Date('2024-01-26'),
    planned_duration: 3,
    actual_duration: 3,
    progress_percentage: 100,
    color: '#22c55e',
    dependencies: ['1'],
    notes: 'Foundation excavation complete',
    created_by: '1',
    created_at: new Date('2024-01-15'),
    updated_at: new Date('2024-01-26')
  },
  {
    id: '3',
    project_id: 'proj-1',
    title: 'Concrete Pour - Foundation',
    description: 'Pour concrete foundation',
    category: 'Foundation',
    location: 'Building A',
    status: 'in_progress',
    priority: 'critical',
    assigned_to: '3',
    start_date: new Date('2024-01-27'),
    end_date: new Date('2024-01-30'),
    planned_duration: 3,
    progress_percentage: 60,
    color: '#3b82f6',
    dependencies: ['2'],
    notes: 'Concrete pour in progress',
    created_by: '1',
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-01-28')
  },
  {
    id: '4',
    project_id: 'proj-1',
    title: 'Steel Frame Installation',
    description: 'Install steel framework',
    category: 'Structural',
    location: 'Building A',
    status: 'pending',
    priority: 'high',
    assigned_to: '3',
    start_date: new Date('2024-02-01'),
    end_date: new Date('2024-02-10'),
    planned_duration: 9,
    progress_percentage: 0,
    color: '#6b7280',
    dependencies: ['3'],
    notes: 'Waiting for concrete to cure',
    created_by: '1',
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-01-28')
  },
  {
    id: '5',
    project_id: 'proj-1',
    title: 'Electrical Rough-in',
    description: 'Install electrical wiring and outlets',
    category: 'Electrical',
    location: 'Building A',
    status: 'pending',
    priority: 'medium',
    assigned_to: '3',
    start_date: new Date('2024-02-06'),
    end_date: new Date('2024-02-15'),
    planned_duration: 9,
    progress_percentage: 0,
    color: '#6b7280',
    dependencies: ['4'],
    notes: 'Electrical rough-in phase',
    created_by: '1',
    created_at: new Date('2024-01-28'),
    updated_at: new Date('2024-01-28')
  },
  {
    id: '6',
    project_id: 'proj-1',
    title: 'Plumbing Installation',
    description: 'Install plumbing systems',
    category: 'Plumbing',
    location: 'Building A',
    status: 'pending',
    priority: 'medium',
    assigned_to: '3',
    start_date: new Date('2024-02-09'),
    end_date: new Date('2024-02-18'),
    planned_duration: 9,
    progress_percentage: 0,
    color: '#6b7280',
    dependencies: ['4'],
    notes: 'Plumbing installation',
    created_by: '1',
    created_at: new Date('2024-01-30'),
    updated_at: new Date('2024-01-30')
  },
  {
    id: '7',
    project_id: 'proj-1',
    title: 'HVAC Installation',
    description: 'Install heating and cooling systems',
    category: 'HVAC',
    location: 'Building A',
    status: 'pending',
    priority: 'medium',
    assigned_to: '3',
    start_date: new Date('2024-02-12'),
    end_date: new Date('2024-02-25'),
    planned_duration: 13,
    progress_percentage: 0,
    color: '#6b7280',
    dependencies: ['5', '6'],
    notes: 'HVAC system installation',
    created_by: '1',
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-01')
  },
  {
    id: '8',
    project_id: 'proj-1',
    title: 'Drywall and Painting',
    description: 'Install drywall and paint interior',
    category: 'Interior',
    location: 'Building A',
    status: 'pending',
    priority: 'low',
    assigned_to: '3',
    start_date: new Date('2024-02-15'),
    end_date: new Date('2024-03-01'),
    planned_duration: 14,
    progress_percentage: 0,
    color: '#6b7280',
    dependencies: ['7'],
    notes: 'Interior finishing work',
    created_by: '1',
    created_at: new Date('2024-02-05'),
    updated_at: new Date('2024-02-05')
  }
];

export const mockDeliveries: Delivery[] = [
  {
    id: 'del-1',
    project_id: 'proj-1',
    task_id: '3',
    supplier_id: '1',
    item: 'Ready-Mix Concrete',
    quantity: 50,
    unit: 'cubic yards',
    planned_date: new Date('2024-01-27'),
    confirmation_status: 'confirmed',
    delivery_address: '123 Construction Site, Metro City',
    notes: 'Foundation concrete delivery',
    confirmed_by: '4',
    confirmed_at: new Date('2024-01-26'),
    created_at: new Date('2024-01-20'),
    updated_at: new Date('2024-01-26')
  },
  {
    id: 'del-2',
    project_id: 'proj-1',
    task_id: '4',
    supplier_id: '2',
    item: 'Steel Beams',
    quantity: 25,
    unit: 'tons',
    planned_date: new Date('2024-02-01'),
    confirmation_status: 'pending',
    delivery_address: '123 Construction Site, Metro City',
    notes: 'Structural steel for frame',
    created_at: new Date('2024-01-25'),
    updated_at: new Date('2024-01-28')
  },
  {
    id: 'del-3',
    project_id: 'proj-1',
    task_id: '5',
    supplier_id: '1',
    item: 'Rebar',
    quantity: 500,
    unit: 'feet',
    planned_date: new Date('2024-01-29'),
    confirmation_status: 'confirmed',
    delivery_address: '123 Construction Site, Metro City',
    notes: 'Reinforcement steel',
    confirmed_by: '4',
    confirmed_at: new Date('2024-01-28'),
    created_at: new Date('2024-01-22'),
    updated_at: new Date('2024-01-28')
  },
  {
    id: 'del-4',
    project_id: 'proj-1',
    task_id: '6',
    supplier_id: '3',
    item: 'Electrical Wire',
    quantity: 1000,
    unit: 'feet',
    planned_date: new Date('2024-02-05'),
    confirmation_status: 'pending',
    delivery_address: '123 Construction Site, Metro City',
    notes: 'Electrical wiring for rough-in',
    created_at: new Date('2024-01-30'),
    updated_at: new Date('2024-01-30')
  }
];

export const mockTaskChangeProposals: TaskChangeProposal[] = [
  {
    id: 'tcp-1',
    task_id: '5',
    proposed_by: '3',
    status: 'pending',
    proposed_start_date: new Date('2024-02-08'),
    proposed_end_date: new Date('2024-02-17'),
    reason: 'Steel delivery delayed, need to push electrical work back',
    impact: 'Minor impact on overall schedule',
    impact_description: 'May delay subsequent tasks by 2 days',
    created_at: new Date('2024-01-29'),
    updated_at: new Date('2024-01-29')
  },
  {
    id: 'tcp-2',
    task_id: '6',
    proposed_by: '3',
    status: 'approved',
    proposed_start_date: new Date('2024-02-11'),
    proposed_end_date: new Date('2024-02-20'),
    reason: 'Coordinate with electrical work to avoid conflicts',
    impact: 'No impact on critical path',
    impact_description: 'Parallel work with electrical systems',
    reviewed_by: '1',
    reviewed_at: new Date('2024-01-30'),
    created_at: new Date('2024-01-29'),
    updated_at: new Date('2024-01-30')
  },
  {
    id: 'tcp-3',
    task_id: '8',
    proposed_by: '3',
    status: 'rejected',
    proposed_start_date: new Date('2024-02-12'),
    proposed_end_date: new Date('2024-02-26'),
    reason: 'Early start requested for interior work',
    impact: 'Would overlap with HVAC installation',
    impact_description: 'Could cause scheduling conflicts',
    reviewed_by: '1',
    reviewed_at: new Date('2024-02-02'),
    created_at: new Date('2024-02-01'),
    updated_at: new Date('2024-02-02')
  }
];

export const mockProject: Project = {
  id: 'proj-1',
  name: 'Metro Office Complex',
  description: 'A modern 5-story office building in downtown Metro City',
  location: '123 Business District, Metro City',
  client: 'Metro Development Group',
  project_manager_id: '1',
  status: 'active',
  start_date: new Date('2024-01-15'),
  end_date: new Date('2024-06-15'),
  budget: 2500000,
  progress_percentage: 35,
  created_at: new Date('2024-01-01'),
  updated_at: new Date()
};

export const getCurrentUser = (role: UserRole = 'project_manager'): User => {
  return mockUsers.find(user => user.role === role) || mockUsers[0];
}; 